In [2]:
# Task 1 — Import NumPy
import numpy as np

# NumPy has been successfully imported and is ready to use.

In [3]:
# Task 2 — Create Your Array
temperatures = [27.5, 29.0, 28.5]
temperature_array = np.array(temperatures) 
print(temperature_array)

[27.5 29.  28.5]


In [4]:
# Task 3 — Inspect the Data Type
print(temperature_array.dtype)
#The concept is Data Type (dtype).
#In NumPy, dtype (data type) tells you what kind of data the array contains.
#This means the array contains decimal numbers (floating-point values).

float64


In [5]:
# Task 4 — Create a 2D Array
weather_data = [
    [27.5, 28.0, 29.5],
    [28.0, 29.0, 30.0]
]
weather_array = np.array(weather_data)
print(weather_array)

[[27.5 28.  29.5]
 [28.  29.  30. ]]


In [8]:
# HANDS-ON 2 Python Lists vs NumPy Arrays
# Task 1 — Try It With Python Lists
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

result = sales_timothy + sales_brenda

print(result)

# 1. Did Python produce: [15, 25, 35]?
# 2. What did Python actually do?
# 3. Why do you think that happened?

# 1. No, Python did not produce [15, 25, 35].
# 2. Python joined (concatenated) the two lists together.
# 3. This happened because the + operator for Python lists
# means concatenation, not element-by-element addition.

[10, 15, 20, 5, 10, 15]


In [9]:
# Task 2 — Convert Them to NumPy Arrays
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

timothy_array = np.array(sales_timothy)
brenda_array = np.array(sales_brenda)
combined_sales = timothy_array + brenda_array
print(combined_sales)

[15 25 35]


In [10]:
# Task 3 — Compare the Results
sales_timothy = [10, 15, 20]
sales_brenda = [5, 10, 15]

# Python lists
list_result = sales_timothy + sales_brenda

# NumPy arrays
array_result = np.array(sales_timothy) + np.array(sales_brenda)

print("Python lists:", list_result)
print("NumPy arrays:", array_result)

# NumPy is useful because it allows us to perform
# mathematical operations on data element by element.
# This makes it easier to calculate, compare, and
# manipulate numerical data in an organized way.

Python lists: [10, 15, 20, 5, 10, 15]
NumPy arrays: [15 25 35]


In [11]:
# HANDS-ON 2 — CHALLENGE
# Online and Store Sales

# Let's create five days of imaginary sales data.

online_sales = np.array([20, 25, 30, 35, 40])
store_sales = np.array([15, 20, 25, 30, 35])

combined_sales = online_sales + store_sales
sales_difference = online_sales - store_sales

print("Online Sales:", online_sales)
print("Store Sales:", store_sales)
print("Combined Sales:", combined_sales)
print("Sales Difference:", sales_difference)

Online Sales: [20 25 30 35 40]
Store Sales: [15 20 25 30 35]
Combined Sales: [35 45 55 65 75]
Sales Difference: [5 5 5 5 5]


In [12]:
# HANDS-ON 3
# MINI PROJECT
# Weather Temperature Analysis with NumPy
# Part 1 — Create the Dataset
import numpy as np
temperatures = [27.5, 29.0, 30.5, 28.0, 31.0, 32.5, 30.0]
temperature_array = np.array(temperatures)
print(temperature_array)

[27.5 29.  30.5 28.  31.  32.5 30. ]


In [13]:
# Part 2 — Understand Your Array
# Question 1 — Is the array 1D or 2D?
print("Dimensions:", temperature_array.ndim)

Dimensions: 1


In [14]:
# Question 2 —Would you describe it as a vector or matrix?
# It is a vector because it is a one-dimensional array.

In [15]:
# Question 3 — What is its data type?
print("Data type:", temperature_array.dtype)

Data type: float64


In [16]:
# Question 4 — How many temperature observations?
print("Number of observations:", temperature_array.size)

Number of observations: 7


In [17]:
# Part 3 — Numerical Operations
# Create the Target Array
target = [28.0, 28.0, 29.0, 28.0, 30.0, 30.0, 29.0]
target_array = np.array(target)
print(target_array)

[28. 28. 29. 28. 30. 30. 29.]


In [18]:
# Task B — Temperature Increase

# Increase every temperature by 2°C.

increased_temperature = temperature_array + 2

print(increased_temperature)

[29.5 31.  32.5 30.  33.  34.5 32. ]


In [20]:
# Part 4 — Think Like an Analyst
#Business Question 1
# Which day had the highest recorded temperature?
highest_temperature = np.max(temperature_array)
highest_day = np.argmax(temperature_array) + 1

print("Highest Temperature:", highest_temperature)
print("Day:", highest_day)

#NumPy is convenient because it allows mathematical operations to be
#performed on all numerical values in an array at once. It also provides
#functions for analysis such as calculating the mean, minimum, maximum,
#and differences.

Highest Temperature: 32.5
Day: 6


In [22]:

# Temperature data
temperatures = np.array([27.5, 29.0, 28.5])

# Target temperature
target = 28.0

# Business Question 1: Highest temperature
highest_temperature = np.max(temperatures)

print("Highest temperature:", highest_temperature, "°C")

# Business Question 2: Days above target
above_target = temperatures > target

print("Temperatures above target:", temperatures[above_target])

# Business Question 3: Temperature difference from target
temperature_difference = temperatures - target

print("Temperature difference:", temperature_difference, "°C")

# Business Question 4: Basic analysis
print("Average temperature:", np.mean(temperatures), "°C")
print("Minimum temperature:", np.min(temperatures), "°C")
print("Maximum temperature:", np.max(temperatures), "°C")

## Business Analysis

### Business Question 1
# Day 2 had the highest recorded temperature at 29.0°C.

### Business Question 2
# Using 28°C as the target, Day 2 and Day 3 were above the target.

### Business Question 3
# The temperature difference shows how much the recorded temperature
# varies from the target. This helps the monitoring team identify
# unusually warm or cool days.

### Business Question 4
# NumPy is convenient because it allows mathematical operations to be
# performed on all numerical values in an array at once. It also provides
# functions for analysis such as calculating the mean, minimum, maximum,
# and differences.

Highest temperature: 29.0 °C
Temperatures above target: [29.  28.5]
Temperature difference: [-0.5  1.   0.5] °C
Average temperature: 28.333333333333332 °C
Minimum temperature: 27.5 °C
Maximum temperature: 29.0 °C


In [23]:
# MINI PROJECT CHALLENGE
# Create Arrays for Three Locations
lagos = np.array([27.5, 29.0, 30.5, 28.0, 31.0])
abuja = np.array([25.0, 28.0, 29.5, 30.0, 32.0])
ibadan = np.array([26.5, 28.5, 29.0, 27.5, 30.5])

print("Lagos:", lagos)
print("Abuja:", abuja)
print("Ibadan:", ibadan)

Lagos: [27.5 29.  30.5 28.  31. ]
Abuja: [25.  28.  29.5 30.  32. ]
Ibadan: [26.5 28.5 29.  27.5 30.5]


In [41]:
# Challenge 1
# Which location recorded the highest temperature on each day?

# Temperature data
lagos = np.array([27.5, 29.0, 30.5, 28.0, 31.0])
abuja = np.array([25.0, 28.0, 29.5, 30.0, 32.0])
ibadan = np.array([26.5, 28.5, 29.0, 27.5, 30.5])

# Combine the data into a 2D array
temperatures = np.array([
    lagos,
    abuja,
    ibadan
])

# Location names
locations = np.array(["Lagos", "Abuja", "Ibadan"])

# Find the location with the highest temperature for each day
highest = np.argmax(temperatures, axis=0)

# Display the result
for day in range(5):
    location = locations[highest[day]]
    temperature = temperatures[highest[day], day]

    print(f"Day {day + 1}: {location} - {temperature}°C")

Day 1: Lagos - 27.5°C
Day 2: Lagos - 29.0°C
Day 3: Lagos - 30.5°C
Day 4: Abuja - 30.0°C
Day 5: Abuja - 32.0°C


In [42]:
# Challenge 2
# Create a calculation that increases every recorded temperature by 1°C.

lagos = np.array([27.5, 29.0, 30.5, 28.0, 31.0])
abuja = np.array([25.0, 28.0, 29.5, 30.0, 32.0])
ibadan = np.array([26.5, 28.5, 29.0, 27.5, 30.5])

# Increase every temperature by 1°C
lagos_new = lagos + 1
abuja_new = abuja + 1
ibadan_new = ibadan + 1

print("Lagos:", lagos_new)
print("Abuja:", abuja_new)
print("Ibadan:", ibadan_new)

Lagos: [28.5 30.  31.5 29.  32. ]
Abuja: [26.  29.  30.5 31.  33. ]
Ibadan: [27.5 29.5 30.  28.5 31.5]


In [43]:
# Challenge 3
# Create a calculation that compares Lagos temperatures with Abuja temperatures
lagos = np.array([27.5, 29.0, 30.5, 28.0, 31.0])
abuja = np.array([25.0, 28.0, 29.5, 30.0, 32.0])
# Compare Lagos temperatures with Abuja temperatures
difference = lagos - abuja
print("Lagos - Abuja:", difference)

Lagos - Abuja: [ 2.5  1.   1.  -2.  -1. ]


# Challenge 4
# Explain why NumPy becomes increasingly useful as the amount of numerical data grows.

NumPy becomes increasingly useful as the amount of numerical data
grows because it allows large amounts of numerical data to be stored
and processed using arrays.

Instead of manually processing each value, NumPy allows us to perform
mathematical operations on entire arrays at once. It also provides
functions for calculating averages, minimums, maximums, comparisons,
and other numerical operations.

Therefore, as a dataset becomes larger, NumPy makes numerical analysis
more convenient, organized, and efficient.

# 1. Project Title
# Weather Temperature Analysis Using NumPy

## Mini Project
# Analysis of Temperature Data for Lagos, Abuja, and Ibadan

# 2. Project Introduction
# Project Introduction
This project uses NumPy to analyze temperature data collected
from three locations: Lagos, Abuja, and Ibadan.

The analysis will involve creating NumPy arrays, inspecting the
data, performing numerical calculations, comparing temperatures,
and identifying important patterns in the data.

The purpose is to demonstrate how NumPy can make numerical data
analysis easier and more efficient.

In [28]:
# 3. Import NumPy
import numpy as np

In [32]:
# 4. Dataset

## Dataset

# The weather station recorded temperatures over five days.

# The locations are:

# - Lagos
# - Abuja
# - Ibadan

# All temperatures are measured in degrees Celsius (°C).

lagos = [27.5, 29.0, 30.5, 28.0, 31.0]

abuja = [25.0, 28.0, 29.5, 30.0, 32.0]

ibadan = [26.5, 28.5, 29.0, 27.5, 30.5]

print("Lagos:", lagos)
print("Abuja:", abuja)
print("Ibadan:", ibadan)

Lagos: [27.5, 29.0, 30.5, 28.0, 31.0]
Abuja: [25.0, 28.0, 29.5, 30.0, 32.0]
Ibadan: [26.5, 28.5, 29.0, 27.5, 30.5]


In [33]:
# 5. Convert Data to NumPy Arrays

lagos = np.array(lagos)
abuja = np.array(abuja)
ibadan = np.array(ibadan)

print("Lagos:", lagos)
print("Abuja:", abuja)
print("Ibadan:", ibadan)

# Now the three datasets are NumPy arrays.

Lagos: [27.5 29.  30.5 28.  31. ]
Abuja: [25.  28.  29.5 30.  32. ]
Ibadan: [26.5 28.5 29.  27.5 30.5]


In [34]:
# 6. Array Inspection

print("Lagos dimensions:", lagos.ndim)
print("Lagos shape:", lagos.shape)
print("Lagos data type:", lagos.dtype)

print("Abuja dimensions:", abuja.ndim)
print("Abuja shape:", abuja.shape)
print("Abuja data type:", abuja.dtype)

print("Ibadan dimensions:", ibadan.ndim)
print("Ibadan shape:", ibadan.shape)
print("Ibadan data type:", ibadan.dtype)

# This means each location has 5 temperature values stored in a 1D NumPy array.


Lagos dimensions: 1
Lagos shape: (5,)
Lagos data type: float64
Abuja dimensions: 1
Abuja shape: (5,)
Abuja data type: float64
Ibadan dimensions: 1
Ibadan shape: (5,)
Ibadan data type: float64


In [38]:
# 7. Numerical Operations
# Challenge 2 — Increase every temperature by 1°C

lagos_plus_1 = lagos + 1
abuja_plus_1 = abuja + 1
ibadan_plus_1 = ibadan + 1

print("Lagos + 1°C:", lagos_plus_1)
print("Abuja + 1°C:", abuja_plus_1)
print("Ibadan + 1°C:", ibadan_plus_1)

Lagos + 1°C: [28.5 30.  31.5 29.  32. ]
Abuja + 1°C: [26.  29.  30.5 31.  33. ]
Ibadan + 1°C: [27.5 29.5 30.  28.5 31.5]


In [39]:
# 8. Lagos vs Abuja Comparison
## Lagos vs Abuja Comparison

#T he Lagos and Abuja temperature arrays were compared by subtracting
# Abuja's temperature from Lagos's temperature.

# A positive result means Lagos was warmer than Abuja, while a negative
# result means Lagos was cooler than Abuja.

difference = lagos - abuja

print("Lagos vs Abuja temperature difference:")
print(difference)

Lagos vs Abuja temperature difference:
[ 2.5  1.   1.  -2.  -1. ]


# 9. Findings

# This is where you should explain the numbers, rather than simply displaying Python output.
## Findings

### Observation 1
The temperature data shows that Lagos recorded the highest temperature
on Days 1, 2, and 3, while Abuja recorded the highest temperature on
Days 4 and 5.

### Observation 2
When every temperature is increased by 1°C, NumPy applies the calculation
to all values in the arrays at once. This demonstrates the usefulness of
vectorized operations.

### Observation 3
The Lagos and Abuja comparison shows that Lagos was warmer than Abuja
on Days 1, 2, and 3. However, Abuja was warmer than Lagos on Days 4 and 5.

### Observation 4
Abuja recorded the highest individual temperature in the dataset,
with 32.0°C on Day 5.

### Observation 5
NumPy makes it easier to work with larger numerical datasets because
mathematical operations can be performed on entire arrays without
manually processing every value.


10. Conclusion

# Conclusion

This project demonstrated how NumPy can be used to analyze temperature
data from multiple locations.

The analysis involved creating NumPy arrays, inspecting their dimensions
and data types, performing calculations, increasing temperatures by 1°C,
and comparing Lagos and Abuja temperatures.

The results show that NumPy provides a convenient way to perform
numerical calculations on multiple values simultaneously. As the amount
of numerical data increases, using NumPy arrays becomes increasingly
useful for efficient analysis and comparison.

This exercise provides a foundation for more advanced data analysis
using Python, NumPy, Pandas, and data visualization tools.
Complete code in one cell
